services:
   postgres:
      image: postgres:latest
      restart: always
      environment:
         POSTGRES_PASSWORD: postgres
         POSTGRES_USER: postgres
         POSTGRES_DB: postgres
         PGDATA: /var/lib/postgresql/data
      ports:
         - "5432:5432"
      volumes:
         - ./volumes/db/data:/var/lib/postgresql/data
         - ./volumes/db/log:/var/log/postgresql
      healthcheck:
         test: [ "CMD-SHELL", "pg_isready" ]
         interval: 10s
         timeout: 5s
         retries: 20

   grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3001:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana-storage:/var/lib/grafana

   api:
      build: .
      restart: always
      ports:
      - "8080:8080"
      environment:
        - DJANGO_DEBUG=1
        - DJANGO_ALLOWED_HOSTS=*
        - DJANGO_SECRET_KEY=АЛЕКСАНДР ШАХОВ Я ВАШ ФАНАТ
        - POSTGRES_HOST=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_PORT=5432
        - POSTGRES_DATABASE=postgres
        - RUNNED_IN_DOCKER=1
        - S3_ID=YCAJEUcCeno6VK6ISP4pVrHPF
        - S3_SECRET=REDACTED
        - S3_ENDPOINT=https://storage.yandexcloud.net
        - LOGGER_ENABLED=1
      depends_on:
        postgres:
          condition: service_healthy

volumes:
   postgres-data:
   grafana-storage: 
