# Generated by Django 5.1.6 on 2025-02-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=256, verbose_name='Логин')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('location', models.CharField(max_length=256, verbose_name='Локация')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=256, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
