# Generated by Django 5.1.6 on 2025-02-14 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        ('campaigns', '0003_campaign_clicked_count_campaign_impressions_count'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adclick',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена клика'),
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=0, verbose_name='Дата показа')),
                ('price', models.IntegerField(default=0, verbose_name='Цена показа')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign', verbose_name='ID рекламы')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='ID клиента')),
            ],
        ),
    ]
