# Generated by Django 5.1.6 on 2025-02-12 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions_limit', models.IntegerField(verbose_name='Лимит показов')),
                ('clicks_limit', models.IntegerField(verbose_name='Лимит кликов')),
                ('cost_per_impression', models.IntegerField(verbose_name='Стоимость показа объявления')),
                ('cost_per_click', models.IntegerField(verbose_name='Стоимость перехода по объявлению')),
                ('ad_title', models.CharField(max_length=255, verbose_name='Название')),
                ('ad_text', models.TextField(verbose_name='Текст объявления')),
                ('start_date', models.IntegerField(verbose_name='День старта показа объявления')),
                ('end_date', models.IntegerField(verbose_name='День окончания показа объявления')),
                ('target_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('ALL', 'All')], max_length=255, verbose_name='Пол аудитории')),
                ('target_age_from', models.IntegerField(verbose_name='Минимальный возраст')),
                ('target_age_to', models.IntegerField(verbose_name='Максимальный возраст')),
                ('target_location', models.CharField(max_length=255, verbose_name='Локация аудитории')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisers.advertiser', verbose_name='ID рекламодателя')),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
            },
        ),
    ]
