# Generated by Django 5.1.6 on 2025-02-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='target_age_from',
            field=models.IntegerField(null=True, verbose_name='Минимальный возраст'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_age_to',
            field=models.IntegerField(null=True, verbose_name='Максимальный возраст'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('ALL', 'All')], max_length=255, null=True, verbose_name='Пол аудитории'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_location',
            field=models.CharField(max_length=255, null=True, verbose_name='Локация аудитории'),
        ),
    ]
