# Generated by Django 5.1.6 on 2025-02-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_target_age_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='clicked_count',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='impressions_count',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
    ]
