# Generated by Django 5.1.6 on 2025-02-16 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_clicked_count_campaign_impressions_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('ALL', 'All')], null=True, verbose_name='Пол')),
                ('age_from', models.IntegerField(null=True, verbose_name='Минимальный возраст')),
                ('age_to', models.IntegerField(null=True, verbose_name='Максимальный возраст')),
                ('location', models.TextField(null=True, verbose_name='Локация')),
            ],
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='target_age_from',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='target_age_to',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='target_gender',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='target_location',
        ),
        migrations.AddField(
            model_name='campaign',
            name='target',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='campaigns.target', verbose_name='Таргет рекламы'),
            preserve_default=False,
        ),
    ]
