# Generated by Django 5.1.6 on 2025-02-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_target_remove_campaign_target_age_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='target',
            new_name='targeting',
        ),
    ]
