# Generated by Django 5.1.6 on 2025-02-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_rename_target_campaign_targeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='decline_reason',
            field=models.TextField(null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='modertaion_status',
            field=models.CharField(choices=[('process', 'Process'), ('fail', 'Fail'), ('ok', 'Ok')], default='process', max_length=255, verbose_name='Статус модерации'),
        ),
    ]
