# Generated by Django 5.1.6 on 2025-02-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_decline_reason_campaign_modertaion_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='decline_reason',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='modertaion_status',
        ),
    ]
