# Generated by Django 5.1.6 on 2025-02-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_remove_campaign_decline_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cost_per_click',
            field=models.FloatField(verbose_name='Стоимость перехода по объявлению'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cost_per_impression',
            field=models.FloatField(verbose_name='Стоимость показа объявления'),
        ),
    ]
