# Generated by Django 5.1.6 on 2025-02-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_alter_campaign_cost_per_click_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='file_url',
            field=models.URLField(null=True),
        ),
    ]
