# Generated by Django 5.1.6 on 2025-02-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_campaign_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='file_url',
            field=models.URLField(max_length=2048, null=True),
        ),
    ]
