# Generated by Django 5.1.6 on 2025-02-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('advertiser_id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рекламодатель',
                'verbose_name_plural': 'Рекламодатели',
            },
        ),
    ]
