# Generated by Django 5.1.6 on 2025-02-21 19:27

import django_s3_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0002_advertiserfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiserfile',
            name='file',
            field=models.FileField(storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='taprod'), upload_to=''),
        ),
    ]
